import type { Metadata } from "next";
import { Geist, Geist_Mono,Fascinate,Charm ,Roboto,Space_Grotesk,Josefin_Sans} from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import HelpButton from "@/myComponents/HelpButton";
import Link from "next/link";


const fascinate = Fascinate({
  variable: "--font-fascinate",
  weight: "400",          // choose available weights
  subsets: ["latin"],     // required for character set
});

const charm = Charm({
  variable: "--font-charm",
  weight: "400",          // choose available weights
  subsets: ["latin"],     // required for character set
});

const roboto = Roboto({
  variable: "--font-roboto",
  weight: "400",          // choose available weights
  subsets: ["latin"],     // required for character set
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-spaceGrotesk",
  weight: "400",          // choose available weights
  subsets: ["latin"],     // required for character set
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
  weight: ["300"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.variable} font-sans antialiased bg-gradient-to-b from-gray-900 via-gray-600 to-gray-300 `}
      >
      <TooltipProvider>
        <div className="w-[80vw]  h-[60px]   flex items-center justify-between mt-5 rounded-full p-5 " >
          <span className="text-white" style={{ fontSize: '4rem' }}>PIXEDIT</span>
          <div className="flex items-center justify-center gap-8">
            <Link href="/my-edits" className="text-white font-bold hover:text-gray-300 transition-colors cursor-pointer" style={{ fontSize: '1.3rem' }}>
              My Edits
            </Link>
            <HelpButton />
          </div>
        </div>
        {children}
      </TooltipProvider>
      </body>
    </html>
  );
}
