import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-b from-gray-900 via-gray-600 to-gray-300 `}
      >
      <div className="w-[80vw]  h-[60px]   flex items-center justify-between mt-5 rounded-full p-5 " >
        <span className="text-white text-6xl font-bold">PIXEDIT</span>
        <div className="flex items-center justify-center gap-8">
          <span className="text-white text-xl font-bold">My Edits</span>
          <span className="text-white text-3xl font-bold bg-gray-900 rounded-md pt-2 pb-2 pl-4 pr-4">?</span>
        </div>
      </div>
        {children}
      </body>
    </html>
  );
}
