import {create} from "zustand";


const useMyStore = create((set)=>({
    imageLink:null,
    setImageLink:(imageLink:string)=>set({imageLink}),
    transformedImageLink:null,
    setTransformedImageLink:(transformedImageLink:string)=>set({transformedImageLink}),
    
    isTransforming:false,
    setIsTransforming:(isTransforming:boolean)=>set({isTransforming}),
    isUploading:false,
    setIsUploading:(isUploading:boolean)=>set({isUploading}),
    // isDownloading:false,
    // setIsDownloading:(isDownloading:boolean)=>set({isDownloading}),
    undoTransFormedImage:null,
    setUndoTransFormedImage:(undoTransFormedImage:string)=>set({undoTransFormedImage}),

    aspectRatio:"",
    setAspectRatio:(aspectRatio:string)=>set({aspectRatio}),
    width:"",
    setWidth:(width:string)=>set({width}),
    height:"",
    setHeight:(height:string)=>set({height}),
    imageFocus:"",
    setImageFocus:(imageFocus:string)=>set({imageFocus}),
    cropMode:"",
    setCropMode:(cropMode:string)=>set({cropMode}),
    zoom:"",
    setZoom:(zoom:string)=>set({zoom}),
    dpr:"",
    setDpr:(dpr:string)=>set({dpr}),
    EditBarNo:1,
    setEditBarNo:(EditBarNo:number)=>set({EditBarNo}),
    layer:"",
    setLayer:(layer:string)=>set({layer}),
    removeBackground:"",
    setRemoveBackground:(removeBackground:string)=>set({removeBackground}),
    changeBackground:"",
    setChangeBackground:(changeBackground:string)=>set({changeBackground}),
    generativeFill:"",
    setGenerativeFill:(generativeFill:string)=>set({generativeFill}),
    editUsingAI:"",
    setEditUsingAI:(editUsingAI:string)=>set({editUsingAI}),
    color:"Red",
    setColor:(color:string)=>set({color}),
    solidColor:"",
    setSolidColor:(solidColor:string)=>set({solidColor}),
   
}))
export default useMyStore;