import {create} from "zustand";


const useMyStore = create((set)=>({
    imageLink:null,
    setImageLink:(imageLink:string)=>set({imageLink}),
    transformedImageLink:null,
    setTransformedImageLink:(transformedImageLink:string)=>set({transformedImageLink}),
    transFormationInstructions:"",
    setTransFormationInstructions:(payload:string)=>set((state:any)=>({
        transFormationInstructions:state.transFormationInstructions + payload
    })),
    isTransforming:false,
    setIsTransforming:(isTransforming:boolean)=>set({isTransforming}),
    isUploading:false,
    setIsUploading:(isUploading:boolean)=>set({isUploading}),
    isDownloading:false,
    setIsDownloading:(isDownloading:boolean)=>set({isDownloading}),

    aspectRatio:"",
    setAspectRatio:(aspectRatio:string)=>set({aspectRatio}),
    width:"",
    setWidth:(width:string)=>set({width}),
    height:"",
    setHeight:(height:string)=>set({height}),
    imageFocus:"",
    setImageFocus:(imageFocus:string)=>set({imageFocus}),
    cropMode:"",
    setCropMode:(cropMode:string)=>set({cropMode}),
    zoom:"",
    setZoom:(zoom:string)=>set({zoom}),
    dpr:"",
    setDpr:(dpr:string)=>set({dpr}),
    EditBarNo:1,
    setEditBarNo:(EditBarNo:number)=>set({EditBarNo}),
    layer:"",
    setLayer:(layer:string)=>set({layer}),
    textFont:20,
    setTextFont:(textFont:number)=>set({textFont}),
    removeBackground:"",
    setRemoveBackground:(removeBackground:string)=>set({removeBackground}),
    changeBackground:"",
    setChangeBackground:(changeBackground:string)=>set({changeBackground}),
    generativeFill:"",
    setGenerativeFill:(generativeFill:string)=>set({generativeFill}),
    editUsingAI:"",
    setEditUsingAI:(editUsingAI:string)=>set({editUsingAI}),
    color:"Red",
    setColor:(color:string)=>set({color}),
    textPositionX:50,
    setTextPositionX:(textPositionX:number)=>set({textPositionX}),
    textPositionY:50,
    setTextPositionY:(textPositionY:number)=>set({textPositionY}),
    solidColor:"",
    setSolidColor:(solidColor:string)=>set({solidColor}),
    Blockwidth:100,
    setBlockwidth:(Blockwidth:number)=>set({Blockwidth}),
    Blockheight:100,
    setBlockheight:(Blockheight:number)=>set({Blockheight}),
   
}))
export default useMyStore;